// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5fp5OOd_mvL8doDnHECLwNd6CFwatOGo',
    appId: '1:107490218692:web:52d67491fcc4ffa90eaf91',
    messagingSenderId: '107490218692',
    projectId: 'smartstyle-app-63929',
    authDomain: 'smartstyle-app-63929.firebaseapp.com',
    storageBucket: 'smartstyle-app-63929.firebasestorage.app',
    measurementId: 'G-HJFYWTQ0MV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCel_25NqLyBgEij1riHlsDLehCXz-5fSo',
    appId: '1:107490218692:android:e8f167d99bed117d0eaf91',
    messagingSenderId: '107490218692',
    projectId: 'smartstyle-app-63929',
    storageBucket: 'smartstyle-app-63929.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9HHKJ2rlDe7_J72yhcyLh2Te1FK5q5d8',
    appId: '1:107490218692:ios:fed868a8ad3b6c390eaf91',
    messagingSenderId: '107490218692',
    projectId: 'smartstyle-app-63929',
    storageBucket: 'smartstyle-app-63929.firebasestorage.app',
    iosBundleId: 'com.example.deneme1',
  );
}
